<a href="https://colab.research.google.com/github/majesticVK/pytorchANN/blob/main/NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [83]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [84]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [85]:
df.shape


(569, 33)

In [86]:
df.drop(columns=['id','Unnamed: 32'], inplace =True)

In [87]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [88]:
X_train, X_test , y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)


In [89]:
scaling = StandardScaler()
X_train = scaling.fit_transform(X_train)
X_test = scaling.transform(X_test)


In [90]:
X_train

array([[-1.05659407, -1.03018792, -1.02909393, ..., -0.37624834,
         0.1585502 ,  0.68810192],
       [ 1.30128949,  1.62457314,  1.4130032 , ...,  0.9817818 ,
        -0.9880234 ,  0.4414685 ],
       [ 2.01521943, -0.49735789,  1.88073159, ...,  0.95044264,
        -0.66620655, -1.06672548],
       ...,
       [-0.36454704,  0.66923472, -0.45355018, ..., -1.62744181,
        -1.01389812, -1.42915969],
       [-0.70646751, -0.28845097, -0.73141256, ..., -0.69710162,
        -1.52654104, -0.83234022],
       [ 0.47247427,  0.06598663,  0.42205322, ...,  0.5027404 ,
        -0.43980274, -1.12629608]])

In [91]:
y_train

426    B
83     M
368    M
511    B
540    B
      ..
497    B
290    B
178    B
297    M
75     M
Name: diagnosis, Length: 455, dtype: object

In [92]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)


In [93]:
y_train

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,

In [94]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [95]:
X_train_tensor.shape

torch.Size([455, 30])

In [96]:
class MysimpleNN():
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1] ,1 , dtype=torch.float64 , requires_grad =True)
    self.bias = torch.zeros(1 , dtype=torch.float64 , requires_grad =True)



  def forward(self,X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred


  def loss(self, y_pred, y_true):
    ep = 1e-8
    y_pred = torch.clamp(y_pred, ep, 1-ep)
    loss = - (y_true * torch.log(y_pred) + (1 - y_true) * torch.log(1 - y_pred)).mean()
    return loss

In [97]:
learning_rate = 0.7
epochs = 100

In [98]:
#model
model = MysimpleNN(X_train_tensor)


for epoch in range(epochs):
  #ff
  y_pred = model.forward(X_train_tensor)

  #loss
  loss = model.loss(y_pred, y_train_tensor)


  #bf
  loss.backward()


  #parameters update
  with torch.no_grad():
    model.weights -= learning_rate *model.weights.grad
    model.bias -= learning_rate *model.bias.grad


  #zeros update
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')


Epoch: 1, Loss: 3.625653161943983
Epoch: 2, Loss: 2.4183481970197582
Epoch: 3, Loss: 1.19007670065416
Epoch: 4, Loss: 0.8351815458403314
Epoch: 5, Loss: 0.7572757526629632
Epoch: 6, Loss: 0.7438932768235796
Epoch: 7, Loss: 0.735265322714878
Epoch: 8, Loss: 0.7311693490626923
Epoch: 9, Loss: 0.7253860031954812
Epoch: 10, Loss: 0.723443004161426
Epoch: 11, Loss: 0.7189864472290023
Epoch: 12, Loss: 0.7184481326180124
Epoch: 13, Loss: 0.7147693339231603
Epoch: 14, Loss: 0.7153249966001576
Epoch: 15, Loss: 0.7121157000292516
Epoch: 16, Loss: 0.7136428165678894
Epoch: 17, Loss: 0.7106844867263261
Epoch: 18, Loss: 0.7131436657722242
Epoch: 19, Loss: 0.7102429970445546
Epoch: 20, Loss: 0.7136177269201717
Epoch: 21, Loss: 0.7105824673433924
Epoch: 22, Loss: 0.7148408999116987
Epoch: 23, Loss: 0.7114823881218308
Epoch: 24, Loss: 0.7165578893164304
Epoch: 25, Loss: 0.7127123049595864
Epoch: 26, Loss: 0.7185038412530552
Epoch: 27, Loss: 0.7140591365223152
Epoch: 28, Loss: 0.7204471359922942
Epoch:

In [102]:
model.bias

tensor([-0.4472], dtype=torch.float64, requires_grad=True)

In [104]:
#model evalute
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.8).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
print(f'accuracy : {accuracy.item()}')


accuracy : 0.7456140518188477
